### ISSUE TITLE
clear_graphics_board() throws error

### ISSUE THREAD

**Issue by bertrtam00** [FraunhIEE-UniKassel-PowSysStability/powfacpy#43]
after creating plots like so: 
![image](https://github.com/FraunhIEE-UniKassel-PowSysStability/powfacpy/assets/26382201/5462d01f-2f64-4e3d-8cee-83e9312b08f1)

the function call 
pfpi.clear_graphics_board()

throws the following error: 
![image](https://github.com/FraunhIEE-UniKassel-PowSysStability/powfacpy/assets/26382201/ced8fc55-3bc2-4be6-9977-06f4bb6c593e)

**Comment by Sciemon** [comment]
Please have a look at the definition of 'clear_graphics board'. Different types of graphics use different methods to close/remove the page. Please check the type of the DataObject where it fails and add the correct method for this type.

**Comment by Sciemon** [comment]
Instead of screenshots it might be better to use
```python
*your code*
```

**Comment by bertrtam00** [comment]
it's (among others)

`x-Axis.PltAxis`
why not just use .Delete()?

**Comment by Sciemon** [comment]
> it's (among others)
> 
> `x-Axis.PltAxis` why not just use .Delete()?

The classes .GrpPage and .SetDeskpage have specific methods to "close" them and I think it is safer to use those instead of simply deleting them (who knows what PF does in the background). 

It stands to question whether objects such as .PltAxis (global axis settings) should be deleted when you want clear the graphics board. For now we have decided that they shouldn't.

**Comment by Sciemon** [comment]
Suggestion:

There should be one method "close_all_graphics_pages"/"clear_all_graphics_pages", that closes the pages and keeps the settings for axis etc. That is actually what most users want to do and the name is more descriptive. 

The method "clear_graphics_board" can stay and will really clear the whole folder (i.e. close pages + delete the axis settings etc.)
