### ISSUE TITLE
get_eigenvalues_of_current_state() fails to export to csv

### ISSUE THREAD

**Issue by nathaliamdc** [FraunhIEE-UniKassel-PowSysStability/powfacpy#73]
# Behavior

The function ``get_eigenvalues_of_current_state()`` from ``PFDynSimInterface`` fails if the export setting in PowerFactory has not been already set to csv before the function call.  

For example, if the export setting happens to be text format, internally ``read_csv`` will fail and it will not be able to read the eigenvalues from the file.

# Possible solution

Add this line [when configuring ComRes](https://github.com/FraunhIEE-UniKassel-PowSysStability/powfacpy/blob/9b35f51b614d5883aa8fede148ea0f9c48f32d84/src/powfacpy/dyn_sim_interface.py#L70) to make sure it exports to csv:

```
comres.iopt_exp = 6 # export to csv format
```

**Comment by Sciemon** [comment]
thanks, will be fixed in the next version

**Comment by Sciemon** [comment]
closed with #81

**Comment by Sciemon** [comment]
closed with #81
