### ISSUE TITLE
Formating in model_exchange (CGMES interface)

### ISSUE THREAD

**Issue by Sciemon** [FraunhIEE-UniKassel-PowSysStability/powfacpy#81]
@martinscripts 

The attributes of the PFCgmesInterface class (will just be called CGMES in future) are all in capital letters. Capital letters are used in Python for example for constants (at module level), but are not so common for class attributes to my knowledge, even if the attributes are not changed often. And it is inconsistent with other classes of *powfacpy*.  So I suggest to use small letters for consistency.

**Comment by martinscripts** [comment]
I think you are right, let's change that. Shall I make a pr or will you sneak it into one of your larger refactorings?

**Comment by Sciemon** [comment]
I can change that in the new structure.

**Comment by Sciemon** [comment]
closed with #82
